package generator

enum class SegmentType {
    BOTTOM_LEFT_CORNER_COMMON_BOTTOM,
    BOTTOM_LEFT_CORNER_COMMON_TOP,

    BOTTOM_LEFT_CORNER_OUT_BORDER_BOTTOM,

    BOTTOM_RIGHT_CORNER_COMMON_BOTTOM,
    BOTTOM_RIGHT_CORNER_COMMON_TOP,

    BOTTOM_RIGHT_CORNER_OUT_BORDER_BOTTOM,

    TOP_LEFT_CORNER_COMMON_BOTTOM,
    TOP_LEFT_CORNER_COMMON_TOP,

    TOP_LEFT_CORNER_OUT_BORDER_TOP,

    TOP_RIGHT_CORNER_COMMON_BOTTOM,
    TOP_RIGHT_CORNER_COMMON_TOP,

    TOP_RIGHT_CORNER_OUT_BORDER_TOP,

    BOTTOM_COMMON_LEFT_BOTTOM,
    BOTTOM_COMMON_LEFT_TOP,

    BOTTOM_COMMON_RIGHT_BOTTOM,
    BOTTOM_COMMON_RIGHT_TOP,

    TOP_COMMON_LEFT_BOTTOM,
    TOP_COMMON_LEFT_TOP,

    TOP_COMMON_RIGHT_BOTTOM,
    TOP_COMMON_RIGHT_TOP,

    LEFT_BEGIN_BOTTOM,
    LEFT_BEGIN_TOP,

    LEFT_COMMON_BOTTOM,
    LEFT_COMMON_TOP,

    LEFT_END_BOTTOM,
    LEFT_END_TOP,

    RIGHT_BEGIN_BOTTOM,
    RIGHT_BEGIN_TOP,
    RIGHT_COMMON_BOTTOM,
    RIGHT_COMMON_TOP,
    RIGHT_END_BOTTOM,
    RIGHT_END_TOP,

    BOTTOM_ROOM_OUT_LEFT_BORDER_BOTTOM,
    BOTTOM_ROOM_OUT_LEFT_BORDER_TOP,
    BOTTOM_ROOM_OUT_RIGHT_BORDER_BOTTOM,
    BOTTOM_ROOM_OUT_RIGHT_BORDER_TOP,
    TOP_ROOM_OUT_LEFT_BORDER_BOTTOM,
    TOP_ROOM_OUT_LEFT_BORDER_TOP,
    TOP_ROOM_OUT_RIGHT_BORDER_BOTTOM,
    TOP_ROOM_OUT_RIGHT_BORDER_TOP,

    ROOM_WALL_START_BOTTOM,
    ROOM_WALL_START_TOP,

    ROOM_WALL_COMMON_BOTTOM,
    ROOM_WALL_COMMON_TOP,

    ROOM_WALL_END_BOTTOM,
    ROOM_WALL_END_TOP,

    NONE
}